all:
    children:
        qa_lacastellana:
           hosts: 
               lacastellanatoqa.wundertec.com:
           vars:
               ansible_ssh_host = 50.16.169.154
               ansible_user = ansible
               ansible_ssh_private_key_file = /home/ansible/.ssh/id_rsa

