FROM centos:7
RUN yum update -y & yum install texlive texlive-latex texlive-collection-xetex git -y
RUN yum install texlive-babel-spanish texlive-biblatex texlive-appendix texlive-appendix texlive-adjustbox texlive-multirrow textlive-wrapfig -y
RUN yum install texlive-babel texlive-babelbib 
RUN git clone https://carlos-zrm:cARLOS123.@github.com/Carlos-ZRM/TesisFinal.git /tesis/
#RUN xelatex -pdf /tesis/TesisFinal/main.tex

#sudo texlive-collection-xetex dnf install texlive-scheme-full
