  version: '3'

  services:
    backend:
      build : ./ecommerce_backend
      container_name : ecommerce_backend
      ports:
        - "8087:8080"
      networks:
        - ecommerce_pro
      restart: always
    frontend:
      build : ./CastellanaEcommerceFrontend
      container_name: pco_frontend_pro 
      ports: 
        - "8116:80"
      environment:
        ENDPOINTS: /ecommerce_backend_pro=http://ecommerce_backend_pro:8080/lacastellana-ecommerce
      depends_on:
        - backend
  networks:
    ecommerce_pro:
      driver: bridge
    