debug: false
trace: false
#~~~~~~~~~~~~~~~~~~~~ S E R V E R ~~~~~~~~~~~~~~~~~~~~~~~~~
server:
  port: 8080
  servlet:
    context-path: /lacastellana-ecommerce
#~~~~~~~~~~~~~~~~~~~~~~~ L O G ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
logging:
  file: log.out
  level:
    org:
      springframework: DEBUG
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
  #++++++++++++++++++++ L O C A L +++++++++++++++++++++++++    
#  path: C:/Program Files/Apache Software Foundation/Apache Tomcat 8.0.27/logs
  #+++++++++++++++++++++++ Q A ++++++++++++++++++++++++++++    
#  path: /var/log/tomcat/onlineportalqa.log
  #+++++++++++++++ P R O D U C C I O N +++++++++++++++++++++    
  path: /opt/bitnami/apache-tomcat/logs/onlineportal.log
#Spring
spring:
  datasource:
    platform: mysql
    driverClassName: com.mysql.jdbc.Driver
    #++++++++++++++++++++++++++++++++++++ Q A +++++++++++++++++++++++++++++++++++++++++ 
    url: jdbc:mysql://ventas-qa.cxwsdw2ago7m.us-east-1.rds.amazonaws.com/lacastellanaQA
    username: ventas
    password: Wund3rVentas01#
#    #++++++++++++++++++++++++++++ P R O D U C C I O N ++++++++++++++++++++++++++++++++++ 
#    url: jdbc:mysql://castellana-ecommerce.cs8h7nua64rl.us-west-2.rds.amazonaws.com/laCastellana
#    username: wundertec
#    password: D7fnRK9C3Ybo0PTfQ

  output:
    ansi:
      enabled: always
  mail:
    # ++++++++++++++++++++++++++++++++ P R U E B A S +++++++++++++++++++++++++++++++++++
#    host: smtp.gmail.com
#    port: 465
#    username: pruebas.email.w@gmail.com
#    password: Wundertec1
#    properties:
#     mail:
#      smtp:
#       auth: true
#       starttls:
#        enable: false
    # +++++++++++++++++++++++++++++ P R O D U C C I O N ++++++++++++++++++++++++++++++++
    host: smtp.office365.com
    port: 587
    username: castellanaonline@lacastellana.com
    password: Cason2017
    protocol: smtp
    properties:
     mail:
      smtp:
       auth: true
       starttls:
        enable: true
       socketFactory:
        port: 587
        class: javax.net.ssl.SSLSocketFactory
        socketFactory: false
#  
  
#SECUTIRY
security:
  secret:
    key: 123581321345589

#BUCKET AWS
aws:
  bucket:
    articulos:
#    DESARROLLO    
#      urls: https://s3.amazonaws.com/la-castellana-erp-development/Catalogo/Articulos/
#     QA
      urls: https://s3.us-west-2.amazonaws.com/la-castellana-erp-qa/Catalogo/Articulos/
#      PRODUCCION
#      urls: https://la-castellana-erp.s3.amazonaws.com/Catalogo/Articulos/
#MERCADO PAGO
mercadoLibre:
  mp:
    paymentURL: https://api.mercadopago.com/v1/payments?
    #PRUEBAS 
    public_key: TEST-8a918572-ee18-4ae2-834b-13c44d77487d
    #PRODUCCION
#    public_key: APP_USR-e01eafd5-86f5-4092-a156-7ebb217a5e77
    timeout: 45
  #PRUEBAS
  acces_token: TEST-7636366106145085-050718-3997893af2e4eca1c87a212145cc8704-299048231
  #PRODUCCION
#  acces_token: APP_USR-7636366106145085-050718-05c4ca55d46e166141518526e9b38f78-299048231
  
