version: '3.8'
services:
    mongodb_container:
        build: Mongo/
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongoadmin
            MONGO_INITDB_ROOT_PASSWORD: secret
        volumes:
            - mongodb_data_container:/data/db
        networks:
            app_net:
              ipv4_address: 172.16.238.9
              aliases:
                - mongodb_container

    flask_container:
        build : .
        depends_on:
            - mongodb_container
        environment:
            MONGO_INITDB_ROOT_USERNAME : mongoadmin 
            MONGO_INITDB_ROOT_PASSWORD  : secret 
            MONGODB_HOST :  mongodb_container
           
        ports :
            - 5000:5000
       
        networks:
            app_net:
              ipv4_address: 172.16.238.10
              aliases:
                - flask_container

volumes:
    mongodb_data_container:

networks:
    app_net:
      ipam:
        driver:  default
        config:
          - subnet: "172.16.238.0/24"